# Generated by Django 4.2.2 on 2023-07-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='update_date',
        ),
    ]
