# Generated by Django 4.2.2 on 2023-07-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_remove_blogpost_update_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog',
        ),
    ]
